### ISSUE TITLE
segfault in bam2feat ?

### ISSUE THREAD

**Issue by roachjm-unc** [leylabmpi/ResMiCo#22] opened 2022-09-22 18:25 UTC
Is anyone else getting a seqfault in bam2feat for large genomes / bams ?

I can run the test data cleanly with the exception of a minor LD_LIBRARY_PATH issue and RHEL8's old libstdc++.  But when I try to run on a more substantial example I get a segfault.

The mean coverage is calculated for all the contigs, samtools sorts the bam, samtools indexes the sorted bam, then bam2feat runs to:

...
[2022-09-22 14:18:20.828] [svc] [info] Processing contig: NODE_12_length_25385_cov_76.665259
[2022-09-22 14:18:20.828] [svc] [info] Getting per-read characteristics
[2022-09-22 14:18:20.828] [svc] [info] Writing features for contig NODE_4_length_29829_cov_75.331800 done.
[2022-09-22 14:18:20.838] [svc] [info] Writing features for contig NODE_5_length_28497_cov_79.222910...

at which point run_cmd() returns:

ValueError: Return code: -11.

When I run CMD separately, same thing:

...
[2022-09-22 14:22:26.942] [svc] [info] Processing contig: NODE_11_length_25922_cov_17.280512
[2022-09-22 14:22:26.955] [svc] [info] Getting per-read characteristics
[2022-09-22 14:22:27.299] [svc] [info] Writing features for contig NODE_4_length_29829_cov_75.331800 done.
[2022-09-22 14:22:27.310] [svc] [info] Writing features for contig NODE_5_length_28497_cov_79.222910...
[2022-09-22 14:22:27.476] [svc] [info] Computing entropy and GC percent
[2022-09-22 14:22:27.480] [svc] [info] Done
[2022-09-22 14:22:27.480] [svc] [info] Gzipped fasta file detected. Using kseq
[2022-09-22 14:22:27.484] [svc] [info] Processing contig: NODE_12_length_25385_cov_76.665259
[2022-09-22 14:22:27.484] [svc] [info] Getting per-read characteristics
Segmentation fault (core dumped)

I can provide the example (approx. 4.5 GB).

Any guidance on about how large is too large?  Or maybe better, about how small a contig is too small?  Is 25000 bp too small?

**Comment by danieldanciu** [comment] 2022-09-28 06:42
The file is definitely not too large. If you can provide the input data and the exact command that you are running, I can try to reproduce and fix.

**Comment by roachjm-unc** [comment] 2022-09-28 11:49
Let me know a good email to use and I can get you the example.

**Comment by roachjm-unc** [comment] 2022-09-28 17:30
Daniel-

Let me know if you receive this email and I'll send you a link to the test data and test script.

Jeff

________________________________________

**Comment by danieldanciu** [comment] 2022-09-29 13:08
Yes, that works!

Thanks,
Daniel

**Comment by roachjm-unc** [comment] 2022-09-29 13:20
Thanks for having a look.

**Comment by danieldanciu** [comment] 2022-10-16 19:30
I just merged https://github.com/leylabmpi/ResMiCo/pull/23 which should fix your issue.

The problem was caused by SAM files that contained unmapped reads. `bam2feat` will now simply skipped unmapped reads (as I think it should).

Can you confirm if this works for you? You would need to pull the latest changes and build `bam2feat` from source (should be trivial). Otherwise you need to wait a couple of days until the conda package gets updated.

**Closed by danieldanciu** 2022-10-16 19:30 UTC

**Comment by roachjm-unc** [comment] 2022-10-19 12:32
@danieldanciu Yes, confirmed.  That solves the problem.  Skipping unmapped reads makes sense to me.  Sorry that took me so long to respond.
